import React from 'react'
import { notFound } from 'next/navigation'
import { PageRenderer } from '../../../components/PageRenderer'
import { headers } from 'next/headers'

export default async function DynamicRoute({
  params,
}: {
  params: Promise<{ slug?: string[] }>
}) {
  const resolvedParams = await params
  const slugArray = resolvedParams.slug || ['home']
  const slug = slugArray.join('/')
  
  const headersList = await headers()
  const tenantConfigStr = headersList.get('x-tenant-config')
  
  if (!tenantConfigStr) {
    // If there's no tenant resolved (e.g. invalid domain), return 404
    notFound()
  }
  
  const tenantConfig = JSON.parse(tenantConfigStr)
  
  // In a real implementation, we would query the Payload CMS local API here:
  // const payload = await getPayload({ config })
  // const pages = await payload.find({
  //   collection: 'pages',
  //   where: {
  //     slug: { equals: slug },
  //     tenantId: { equals: tenantConfig.id }
  //   }
  // })
  // const page = pages.docs[0]
  
  // Mock page for boilerplate
  const page = {
    title: `Mock Page: ${slug}`,
    layout: [
      {
        blockType: 'hero',
        title: `Welcome to ${tenantConfig.name}`,
        subtitle: 'This is a mock page generated by the boilerplate.',
      }
    ]
  }

  if (!page) {
    notFound()
  }

  return (
    <PageRenderer page={page} tenant={tenantConfig} />
  )
}
