import Image from 'next/image'
import { Accordion, FrontendForm } from '../components/Interactive'
import { CardGrid, FormField, PageHero, SectionHeader } from '../components/Shared'
import { image } from '../data/site'

const FormSubmit = ({ label }: { label: string }) => <button className="zz-btn zz-btn-primary zz-form-submit" type="submit">{label}</button>

export function ContactPage() {
  const faqs: Array<[string,string]> = [
    ['Do you offer vegetarian options?', 'Yes, we have a dedicated vegetarian and vegan menu, including our signature Mushroom Shoyu Ramen and various plant-based sushi rolls.'],
    ['Is there a dress code?', 'We embrace a smart casual dress code. We ask that guests refrain from wearing athletic wear or beachwear.'],
    ['Do you have parking?', 'Yes, we offer complimentary valet parking for all our dining guests.'],
  ]
  return <><PageHero background="chef.png" title="Get in Touch" text="We would love to hear from you" /><section className="zz-section-dark"><div className="zz-container"><div className="zz-info-grid"><article><h3>Location</h3><p>Zuru Zuru, Delhi, India 110049</p></article><article><h3>Opening Hours</h3><p>1:00 PM - 4:00 PM &amp; 7:00 PM - 10:30 PM (Lunch &amp; Dinner)<br />4:00 PM - 7:00 PM (Tempura, Gyoza &amp; Cold Ramen)</p></article><article><h3>Contact</h3><p>+91 11 4052 7373<br />hello@zuruzuru.in</p></article></div></div></section><section><div className="zz-container zz-contact-grid"><div><h2>Send a Message</h2><p>Have a question or feedback? We&apos;d love to hear from you.</p><FrontendForm className="zz-form-grid"><FormField label="Name" name="name" /><FormField label="Email" name="email" type="email" /><FormField label="Subject" name="subject" options={['General Inquiry','Feedback','Careers','Press & Media']} placeholder="Select a subject" type="select" /><FormField label="Message" name="message" type="textarea" /><FormSubmit label="Send Message" /></FrontendForm></div><iframe allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.664878206969!2d77.21404107528574!3d28.549791487834575!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce21213401737%3A0xe54e616c68bf5bf6!2sNew%20Delhi%2C%20Delhi%20110049!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin" title="Zuru Zuru location in New Delhi" /></div></section><section className="zz-section-alt"><div className="zz-container"><SectionHeader title="Frequently Asked Questions" text="Quick answers to common inquiries" /><Accordion items={faqs} /></div></section></>
}

export function CateringPage() {
  const events = [
    { title:'Wedding Receptions', image:'hero_sushi.png', description:'Make your special day unforgettable with a spectacular feast of premium sushi, elegant izakaya dishes, and live action stations that will dazzle your guests.' },
    { title:'Corporate Events', image:'interior.png', description:'From executive board lunches to grand gala dinners, our corporate catering ensures a sophisticated and smooth dining experience for your business associates.' },
    { title:'Birthday Celebrations', image:'gyoza_tempura.png', description:'Turn your party into a lively culinary celebration. We provide interactive food stations, customized sake menus, and vibrant flavors for all ages.' },
    { title:'Outdoor Gatherings', image:'hero_ramen.png', description:'Enjoy our robust yakitori grills and refreshing Japanese salads in the open air. Perfect for summer garden parties and outdoor retreats.' },
  ]
  const steps = [
    {title:'1. Consultation',description:'Contact us to discuss your event size, dietary requirements, and specific vision.'},{title:'2. Tasting & Menu',description:'Experience a private tasting session and finalize your bespoke menu selection.'},{title:'3. Preparation',description:'We coordinate logistics, staffing, and equipment with your venue managers.'},{title:'4. Execution',description:'Relax and enjoy your event as our expert team delivers a flawless culinary experience.'},
  ]
  return <><PageHero background="hero_sushi.png" title="Catering Services" text="Bring the exceptional taste of Zuru Zuru to your chosen venue" /><section><div className="zz-container"><SectionHeader eyebrow="Our Expertise" title="Catered Events" text="We offer bespoke catering solutions tailored perfectly to the scale and style of your gathering." /><CardGrid cards={events} columns={2} /></div></section><section className="zz-section-dark"><div className="zz-container"><SectionHeader dark eyebrow="The Process" title="How It Works" /><CardGrid cards={steps} columns={4} /></div></section><section><div className="zz-container zz-booking-grid"><div><h3>Sample Catering Menu</h3><p>This is a representative selection. We customize menus for every event.</p><h4>Hors d&apos;Oeuvres</h4><p><strong>Wagyu Beef Tataki</strong><br />Ponzu, crispy garlic, microgreens</p><p><strong>Spicy Tuna Tartare</strong><br />Served on crispy rice cakes</p><p><strong>Mushroom Gyoza (V)</strong><br />Truffle oil, scallion soy dipping sauce</p><h4>Live Stations</h4><p>Premium Sushi Bar · Robata Grill</p><h4>Main Courses</h4><p>Miso Black Cod · Braised Pork Belly (Kakuni)</p></div><div className="zz-form-panel"><h3>Book Catering</h3><FrontendForm className="zz-form-grid"><FormField label="Full Name" name="name" /><FormField label="Company (Optional)" name="company" /><FormField label="Email" name="email" type="email" /><FormField label="Phone" name="phone" type="tel" /><FormField label="Event Date" name="date" type="date" /><FormField label="Est. Guest Count" name="guests" type="number" /><FormField label="Event Location/Venue" name="venue" /><FormField label="Event Details & Requests" name="details" type="textarea" /><FormSubmit label="Request Proposal" /></FrontendForm></div></div></section></>
}

export function PrivateDiningPage() {
  const experiences = [
    ['VIP Room','Our most exclusive space featuring traditional tatami seating options with modern comfort. Accommodates up to 12 guests.','interior.png'],
    ['Corporate Dinners','A sophisticated environment perfect for closing deals or rewarding your team. Fully equipped with discreet A/V options. Accommodates up to 24 guests.','chef.png'],
    ['Milestone Birthdays',"Celebrate life's special moments with a customized dining experience, complete with a personalized cake and special Izakaya treats.",'gyoza_tempura.png'],
    ['Intimate Weddings','A beautiful, romantic setting for micro-weddings and rehearsal dinners, tailored specifically to your love story.','hero_sushi.png'],
    ["Chef's Table Omakase",'An interactive, front-row seat to culinary mastery. Watch our Executive Chef prepare an exclusive 12-course tasting menu right before your eyes.','chef.png'],
    ['Sake Tasting Sessions',"A guided journey through Japan's finest rice wines, led by our in-house sommelier, paired perfectly with Izakaya bites.",'interior.png'],
  ].map(([title,description,asset])=>({title,description,image:asset}))
  const packages = [
    {title:'Silver Tier',meta:'₹4,500 / guest',description:'5-Course Izakaya Menu · Welcome Sake Cocktail · Private Room Access (3 Hours) · Standard Table Decor · Dedicated Server'},
    {title:'Gold Tier',meta:'₹7,500 / guest · Most Popular',description:'8-Course Signature Menu · Premium Sake Pairing (3 Pours) · Private Room Access (4 Hours) · Floral Centerpieces · Dedicated Sommelier'},
    {title:'Platinum Tier',meta:'₹12,000 / guest',description:"12-Course Omakase Menu · Exclusive Rare Sake Pairing · Private Room Access (Entire Evening) · Custom Menus & Decor · Take-home Chef's Gift Box"},
  ]
  return <><PageHero background="hero_ramen.png" title="Private Dining" text="Exclusive spaces for your most memorable occasions" /><section className="zz-section-alt"><div className="zz-container zz-split-layout"><div><h2>An Intimate Culinary Journey</h2><p>Elevate your special moments with our bespoke private dining experiences at Zuru Zuru Izakaya. Designed for discerning guests who appreciate exclusivity and personalized service, our private rooms blend traditional Japanese aesthetics with modern luxury.</p><p>Whether you&apos;re hosting an intimate gathering, a corporate dinner, or celebrating a milestone, our dedicated team will ensure every detail—from custom menus to perfectly paired sake—is executed flawlessly.</p></div><div className="zz-story-image"><Image alt="Private dining at Zuru Zuru" fill sizes="50vw" src={image('interior.png')} /></div></div></section><section><div className="zz-container"><SectionHeader eyebrow="Exquisite Settings" title="Dining Experiences" /><CardGrid cards={experiences} /></div></section><section className="zz-section-dark"><div className="zz-container"><SectionHeader dark eyebrow="Curated Offerings" title="Luxury Packages" text="Select from our thoughtfully crafted packages for your private event." /><CardGrid cards={packages} /></div></section><ProposalForm title="Request a Proposal" /></>
}

function ProposalForm({ title }: { title: string }) {
  return <section className="zz-section-alt"><div className="zz-container zz-form-panel zz-form-narrow"><h2>{title}</h2><FrontendForm className="zz-form-grid"><FormField label="First Name" name="firstName" /><FormField label="Last Name" name="lastName" /><FormField label="Email Address" name="email" type="email" /><FormField label="Phone Number" name="phone" type="tel" /><FormField label="Event Type" name="event" options={['Corporate Dinner','Birthday/Anniversary','Wedding Reception','Other']} placeholder="Select event type" type="select" /><FormField label="Number of Guests" name="guests" type="number" /><FormField label="Preferred Date" name="date" type="date" /><FormField label="Additional Details" name="details" type="textarea" /><FormSubmit label="Submit Inquiry" /></FrontendForm></div></section>
}

export function EventsPage() {
  const upcoming = [
    {title:'Live Tokyo Jazz',meta:'Music · Every Friday, 8 PM',image:'interior.png',description:'Immerse yourself in the soulful sounds of live jazz while enjoying our signature cocktails and Izakaya bites. A perfect start to your weekend.'},
    {title:'Premium Sake Tasting',meta:'Tasting · August 15, 7 PM',image:'hero_sushi.png',description:"Join our resident Sommelier for an exclusive journey through Japan's finest regional sakes, perfectly paired with seasonal Otsumami."},
    {title:"Omakase Chef's Table",meta:'Exclusive · August 25, 7:30 PM',image:'chef.png',description:'An intimate 12-course dining experience hosted by Executive Chef Kenji. Watch as he prepares seasonal delicacies right before your eyes.'},
    {title:'Matsuri Street Food Festival',meta:'Culture · September 5-7',image:'gyoza_tempura.png',description:"We're transforming our patio into a vibrant Japanese summer festival! Enjoy yakitori stalls, takoyaki, games, and festive decorations."},
  ]
  const regular = [{title:'Ramen Masterclass',description:'Learn the secrets of our rich tonkotsu broth and handmade noodles in this hands-on Sunday afternoon workshop.'},{title:'Sake & Sushi Nights',description:"Every Tuesday, enjoy 50% off select sake carafes and complimentary chef's choice sushi rolls with your first order."},{title:'Corporate Mixology',description:'Book our private bar for your team and learn how to craft Japanese-inspired cocktails using matcha, yuzu, and shochu.'}]
  return <><PageHero background="interior.png" title="Events & Experiences" text="Discover exclusive culinary events, cultural celebrations, and immersive dining experiences at Zuru Zuru Izakaya. Join us in celebrating the art of Japanese cuisine." /><section><div className="zz-container"><SectionHeader title="Upcoming Events" text="Reserve your spot for our special limited-time experiences." /><CardGrid cards={upcoming} columns={2} /></div></section><section className="zz-section-dark"><div className="zz-container"><SectionHeader dark title="Regular Experiences" text="Immerse yourself in our weekly and monthly recurring events." /><CardGrid cards={regular} /></div></section><ProposalForm title="Inquire About an Event" /></>
}

export function ReservationPage() {
  return <section className="zz-reservation-page"><div className="zz-container zz-reservation-grid"><div className="zz-reservation-form"><h2>Book a Table</h2><p>Join us for an unforgettable dining experience.</p><FrontendForm className="zz-form-grid"><FormField label="Full Name" name="name" /><FormField label="Phone Number" name="phone" type="tel" /><FormField label="Email Address" name="email" type="email" /><FormField label="Number of Guests" name="guests" options={['1 Person','2 People','3 People','4 People','5 People','6 People','7 People','8+ People (Contact Us)']} type="select" /><FormField label="Occasion (Optional)" name="occasion" options={['Standard Dining','Birthday','Anniversary','Business Meal','Date Night']} type="select" /><FormField label="Date" name="date" type="date" /><FormField label="Time" name="time" options={['12:00 PM','12:30 PM','1:00 PM','1:30 PM','2:00 PM','6:30 PM','7:00 PM','7:30 PM','8:00 PM','8:30 PM','9:00 PM','9:30 PM']} type="select" /><FormField label="Special Requests (Optional)" name="requests" type="textarea" /><FormSubmit label="Confirm Reservation" /></FrontendForm></div><aside><h3>Details</h3><h4>Phone Reservations</h4><p>Prefer to speak with us? Call us at +91 11 4052 7373 between 10:00 AM and 10:00 PM daily.</p><h4>Large Parties &amp; Events</h4><p>For groups of 8 or more, or private dining inquiries, please contact our events team directly to discuss customized set menus.</p><h4>Cancellation Policy</h4><p>We kindly ask for at least 24 hours notice for any cancellations or adjustments to your reservation.</p><h4>Location</h4><p>Zuru Zuru, Delhi, India 110049</p></aside></div></section>
}
