import {
  ArrowRightIcon,
  BowlFoodIcon,
  BriefcaseIcon,
  BuildingsIcon,
  CakeIcon,
  CalendarIcon,
  CaretDownIcon,
  CaretRightIcon,
  CheckIcon,
  ChefHatIcon,
  ClockIcon,
  CookingPotIcon,
  FacebookLogoIcon,
  FireIcon,
  ForkKnifeIcon,
  HandHeartIcon,
  HandsClappingIcon,
  HeartIcon,
  InstagramLogoIcon,
  LeafIcon,
  MapPinIcon,
  MartiniIcon,
  MedalIcon,
  MopedIcon,
  PepperIcon,
  PhoneIcon,
  PlantIcon,
  ShieldCheckIcon,
  SparkleIcon,
  StarIcon,
  SunIcon,
  TruckIcon,
  YoutubeLogoIcon,
} from '@phosphor-icons/react/dist/ssr'
import type { IconProps } from '@phosphor-icons/react'
import type { ComponentType } from 'react'

const icons: Record<string, ComponentType<IconProps>> = {
  arrow: ArrowRightIcon,
  bowl: BowlFoodIcon,
  briefcase: BriefcaseIcon,
  building: BuildingsIcon,
  cake: CakeIcon,
  calendar: CalendarIcon,
  caretDown: CaretDownIcon,
  caretRight: CaretRightIcon,
  check: CheckIcon,
  chef: ChefHatIcon,
  clock: ClockIcon,
  coriander: PlantIcon,
  delivery: TruckIcon,
  diamond: SparkleIcon,
  event: BuildingsIcon,
  facebook: FacebookLogoIcon,
  fire: FireIcon,
  ghee: CookingPotIcon,
  handcrafted: HandHeartIcon,
  hands: HandsClappingIcon,
  heart: HeartIcon,
  instagram: InstagramLogoIcon,
  leaf: LeafIcon,
  map: MapPinIcon,
  martini: MartiniIcon,
  medal: MedalIcon,
  moped: MopedIcon,
  pepper: PepperIcon,
  phone: PhoneIcon,
  shield: ShieldCheckIcon,
  spice: SparkleIcon,
  star: StarIcon,
  sun: SunIcon,
  utensils: ForkKnifeIcon,
  wedding: HeartIcon,
  youtube: YoutubeLogoIcon,
}

export function Icon({ name, weight, ...props }: { name: string } & IconProps) {
  const PhosphorIcon = icons[name] ?? SparkleIcon
  return <PhosphorIcon aria-hidden="true" weight={weight ?? 'regular'} {...props} />
}
