/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    media: Media;
    pages: Page;
    'menu-categories': MenuCategory;
    'menu-items': MenuItem;
    testimonials: Testimonial;
    teammembers: Teammember;
    events: Event;
    reservations: Reservation;
    'blog-posts': BlogPost;
    locations: Location;
    faqs: Faq;
    'contact-submissions': ContactSubmission;
    gallery: Gallery;
    'site-settings': SiteSetting;
    nav: Nav;
    footer: Footer;
    seo: Seo;
    redirects: Redirect;
    rooms: Room;
    amenities: Amenity;
    packages: Package;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'menu-categories': MenuCategoriesSelect<false> | MenuCategoriesSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    teammembers: TeammembersSelect<false> | TeammembersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    nav: NavSelect<false> | NavSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('super_admin' | 'tenant_admin' | 'tenant_member')[];
  tenants?: (number | Tenant)[] | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Auto-generated if left blank. Used for internal routing and data isolation.
   */
  slug?: string | null;
  type: 'restaurant' | 'hospitality' | 'cloud_kitchen';
  /**
   * Assign if this is a sub-brand of another tenant.
   */
  parentTenant?: (number | null) | Tenant;
  isActive?: boolean | null;
  /**
   * If true, this tenant acts as the fallback for unknown domains.
   */
  isPrimary?: boolean | null;
  /**
   * Domains that should route to this tenant (e.g. ghee-roast.com)
   */
  domains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  settings?: {
    defaultLocale?: string | null;
    timezone?: string | null;
    currency?: string | null;
  };
  contact?: {
    contactEmail?: string | null;
    contactPhone?: string | null;
  };
  branding?: {
    primaryColor?: string | null;
    accentColor?: string | null;
    backgroundColor?: string | null;
    logo?: (number | null) | Media;
    favicon?: (number | null) | Media;
  };
  typography?: {
    headingFont?: string | null;
    bodyFont?: string | null;
    decorativeFont?: string | null;
    headingTransform?: ('none' | 'uppercase' | 'capitalize' | 'lowercase') | null;
    cardRadius?: string | null;
  };
  features?: {
    enableMenu?: boolean | null;
    enableBlog?: boolean | null;
    enableReservations?: boolean | null;
    enableCatering?: boolean | null;
    enableGallery?: boolean | null;
  };
  layout?: {
    preset?: ('classic' | 'elegant' | 'grand') | null;
    headerStyle?: ('transparent-scroll' | 'fixed-dark' | 'centered-logo') | null;
    footerStyle?: ('light' | 'dark') | null;
  };
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  /**
   * Important for SEO and Accessibility.
   */
  alt: string;
  title?: string | null;
  caption?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional categorization folder.
   */
  folder?: string | null;
  /**
   * Set X and Y coordinates (0 to 100) for image cropping.
   */
  focalPoint?: {
    x?: number | null;
    y?: number | null;
  };
  uploadedBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  title: string;
  /**
   * Auto-generated if left blank. (e.g., "about-us")
   */
  slug?: string | null;
  parent?: (number | null) | Page;
  /**
   * If checked, this page loads at the root URL (/).
   */
  isHomePage?: boolean | null;
  template?: ('default' | 'blank' | 'landing') | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  /**
   * Construct the page visually using dynamic blocks.
   */
  layout?:
    | {
        content?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mockBlock';
      }[]
    | null;
  showInNavigation?: boolean | null;
  navigationLabel?: string | null;
  sortOrder?: number | null;
  redirect?: {
    enableRedirect?: boolean | null;
    redirectUrl?: string | null;
    permanent?: boolean | null;
  };
  metaTitle?: string | null;
  metaDescription?: string | null;
  metaImage?: (number | null) | Media;
  canonicalUrl?: string | null;
  noIndex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories".
 */
export interface MenuCategory {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  title: string;
  /**
   * Auto-generated if left blank.
   */
  slug?: string | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  icon?: (number | null) | Media;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  title: string;
  /**
   * Auto-generated if left blank.
   */
  slug?: string | null;
  /**
   * Optional ID for POS integration.
   */
  sku?: string | null;
  description?: string | null;
  category: number | MenuCategory;
  displayOrder?: number | null;
  price: number;
  taxCategory?: string | null;
  /**
   * e.g. Regular vs Large, or add-ons.
   */
  pricingOptions?:
    | {
        label: string;
        price: number;
        id?: string | null;
      }[]
    | null;
  dietary?: ('Veg' | 'Non-Veg' | 'Vegan' | 'Gluten-Free' | 'Keto' | 'Halal')[] | null;
  spiceLevel?: ('none' | 'mild' | 'medium' | 'hot' | 'extra_hot') | null;
  allergens?: ('Peanuts' | 'Tree Nuts' | 'Dairy' | 'Eggs' | 'Soy' | 'Wheat' | 'Fish' | 'Shellfish')[] | null;
  calories?: number | null;
  servingSize?: string | null;
  /**
   * Preparation time in minutes.
   */
  prepTime?: number | null;
  image?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  isAvailable?: boolean | null;
  isFeatured?: boolean | null;
  stockStatus?: ('in_stock' | 'low_stock' | 'out_of_stock') | null;
  /**
   * e.g., "Lunch Only (11am - 3pm)"
   */
  availabilityTime?: string | null;
  recommendedItems?: (number | MenuItem)[] | null;
  upsellItems?: (number | MenuItem)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  customerName: string;
  /**
   * e.g. Local Food Critic, Regular Guest
   */
  customerRole?: string | null;
  rating: number;
  review: string;
  photo?: (number | null) | Media;
  isFeatured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teammembers".
 */
export interface Teammember {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  customerName: string;
  email: string;
  phone: string;
  date: string;
  time: string;
  guests: number;
  status?: ('pending' | 'confirmed' | 'cancelled' | 'completed') | null;
  specialOccasion?: ('birthday' | 'anniversary' | 'business' | 'other') | null;
  /**
   * Specific location if multi-location is active.
   */
  branch?: string | null;
  bookingSource?: string | null;
  /**
   * For future POS / table management sync.
   */
  tableNumber?: string | null;
  /**
   * Customer requests.
   */
  notes?: string | null;
  /**
   * Staff notes. Not visible to customer.
   */
  internalNotes?: string | null;
  notificationsSent?: boolean | null;
  reminderStatus?: ('none' | 'sent' | 'confirmed') | null;
  cancellationReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  title: string;
  /**
   * Auto-generated if left blank.
   */
  slug?: string | null;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  heroImage?: (number | null) | Media;
  status?: ('draft' | 'published' | 'archived') | null;
  author?: (number | null) | User;
  /**
   * Scheduled Publishing: Set a future date to automatically publish.
   */
  publishedDate?: string | null;
  /**
   * Scheduled Unpublish: Set a date to automatically archive.
   */
  unpublishDate?: string | null;
  isFeatured?: boolean | null;
  /**
   * Keep at the top of the blog index.
   */
  isPinned?: boolean | null;
  showTableOfContents?: boolean | null;
  categories?: string[] | null;
  tags?: string[] | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  metaImage?: (number | null) | Media;
  relatedPosts?: (number | BlogPost)[] | null;
  relatedMenuItems?: (number | MenuItem)[] | null;
  readingTimeMinutes?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  name: string;
  email: string;
  phone?: string | null;
  type: 'general' | 'catering' | 'franchise' | 'careers';
  status?: ('new' | 'read' | 'resolved') | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  title: string;
  category?: ('food' | 'ambiance' | 'events' | 'kitchen' | 'exterior') | null;
  media: number | Media;
  isFeatured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage core operational settings for this tenant. Limited to one document per tenant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  businessName: string;
  legalName?: string | null;
  taxId?: string | null;
  cuisineType?: string | null;
  priceRange?: ('$' | '$$' | '$$$' | '$$$$') | null;
  mapsUrl?: string | null;
  mapsEmbedCode?: string | null;
  hours?:
    | {
        day?: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday') | null;
        openTime?: string | null;
        closeTime?: string | null;
        isClosed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  whatsappNumber?: string | null;
  deliverySettings?: {
    enableDelivery?: boolean | null;
    deliveryUrls?:
      | {
          platform?: string | null;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  reservationSettings?: {
    provider?: ('internal' | 'opentable' | 'resy') | null;
    providerUrl?: string | null;
  };
  socials?:
    | {
        platform?: ('facebook' | 'instagram' | 'twitter' | 'tiktok' | 'youtube') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  googleAnalyticsId?: string | null;
  facebookPixelId?: string | null;
  customHeaderScripts?: string | null;
  customFooterScripts?: string | null;
  maintenanceMode?: boolean | null;
  showAnnouncementBar?: boolean | null;
  announcementText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the primary header navigation for this tenant. Limited to one document per tenant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav".
 */
export interface Nav {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  links?:
    | (
        | {
            label: string;
            type?: ('page' | 'internal' | 'external' | 'anchor') | null;
            page?: (number | null) | Page;
            url?: string | null;
            /**
             * Icon class name (e.g., fas fa-home)
             */
            icon?: string | null;
            badge?: string | null;
            newTab?: boolean | null;
            nofollow?: boolean | null;
            visibility?: ('public' | 'logged_in' | 'logged_out') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'link';
          }
        | {
            label: string;
            columns?:
              | {
                  title?: string | null;
                  links?: (number | Page)[] | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'megaMenu';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the footer layout for this tenant. Limited to one document per tenant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Links below the main footer (e.g., Privacy Policy, Terms of Service).
   */
  bottomLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Use {year} to dynamically inject the current year.
   */
  copyright?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage global fallback SEO metadata for this tenant. Limited to one document per tenant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  /**
   * Use %s where the specific page title should be injected.
   */
  metaTitlePattern?: string | null;
  metaDescription?: string | null;
  /**
   * Comma separated keywords.
   */
  keywords?: string | null;
  canonicalUrl?: string | null;
  robots?: ('index, follow' | 'noindex, follow' | 'index, nofollow' | 'noindex, nofollow') | null;
  ogTitle?: string | null;
  ogDescription?: string | null;
  defaultOGImage?: (number | null) | Media;
  ogSiteName?: string | null;
  twitterCard?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
  /**
   * @username for the website used in the card footer.
   */
  twitterSite?: string | null;
  /**
   * @username for the content creator / author.
   */
  twitterCreator?: string | null;
  /**
   * Global JSON-LD schema (e.g., Organization or LocalBusiness).
   */
  jsonLd?: string | null;
  googleSiteVerification?: string | null;
  bingSiteVerification?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  /**
   * Super Admins may select a tenant. Other users are assigned from trusted tenant context.
   */
  tenantId: number | Tenant;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'menu-categories';
        value: number | MenuCategory;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'teammembers';
        value: number | Teammember;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'reservations';
        value: number | Reservation;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'nav';
        value: number | Nav;
      } | null)
    | ({
        relationTo: 'footer';
        value: number | Footer;
      } | null)
    | ({
        relationTo: 'seo';
        value: number | Seo;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'rooms';
        value: number | Room;
      } | null)
    | ({
        relationTo: 'amenities';
        value: number | Amenity;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  tenants?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  parentTenant?: T;
  isActive?: T;
  isPrimary?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        defaultLocale?: T;
        timezone?: T;
        currency?: T;
      };
  contact?:
    | T
    | {
        contactEmail?: T;
        contactPhone?: T;
      };
  branding?:
    | T
    | {
        primaryColor?: T;
        accentColor?: T;
        backgroundColor?: T;
        logo?: T;
        favicon?: T;
      };
  typography?:
    | T
    | {
        headingFont?: T;
        bodyFont?: T;
        decorativeFont?: T;
        headingTransform?: T;
        cardRadius?: T;
      };
  features?:
    | T
    | {
        enableMenu?: T;
        enableBlog?: T;
        enableReservations?: T;
        enableCatering?: T;
        enableGallery?: T;
      };
  layout?:
    | T
    | {
        preset?: T;
        headerStyle?: T;
        footerStyle?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenantId?: T;
  alt?: T;
  title?: T;
  caption?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  folder?: T;
  focalPoint?:
    | T
    | {
        x?: T;
        y?: T;
      };
  uploadedBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenantId?: T;
  title?: T;
  slug?: T;
  parent?: T;
  isHomePage?: T;
  template?: T;
  status?: T;
  publishedAt?: T;
  layout?:
    | T
    | {
        mockBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  showInNavigation?: T;
  navigationLabel?: T;
  sortOrder?: T;
  redirect?:
    | T
    | {
        enableRedirect?: T;
        redirectUrl?: T;
        permanent?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  canonicalUrl?: T;
  noIndex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories_select".
 */
export interface MenuCategoriesSelect<T extends boolean = true> {
  tenantId?: T;
  title?: T;
  slug?: T;
  isActive?: T;
  sortOrder?: T;
  icon?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  tenantId?: T;
  title?: T;
  slug?: T;
  sku?: T;
  description?: T;
  category?: T;
  displayOrder?: T;
  price?: T;
  taxCategory?: T;
  pricingOptions?:
    | T
    | {
        label?: T;
        price?: T;
        id?: T;
      };
  dietary?: T;
  spiceLevel?: T;
  allergens?: T;
  calories?: T;
  servingSize?: T;
  prepTime?: T;
  image?: T;
  gallery?: T;
  isAvailable?: T;
  isFeatured?: T;
  stockStatus?: T;
  availabilityTime?: T;
  recommendedItems?: T;
  upsellItems?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  tenantId?: T;
  customerName?: T;
  customerRole?: T;
  rating?: T;
  review?: T;
  photo?: T;
  isFeatured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teammembers_select".
 */
export interface TeammembersSelect<T extends boolean = true> {
  tenantId?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  tenantId?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  tenantId?: T;
  customerName?: T;
  email?: T;
  phone?: T;
  date?: T;
  time?: T;
  guests?: T;
  status?: T;
  specialOccasion?: T;
  branch?: T;
  bookingSource?: T;
  tableNumber?: T;
  notes?: T;
  internalNotes?: T;
  notificationsSent?: T;
  reminderStatus?: T;
  cancellationReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  tenantId?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  heroImage?: T;
  status?: T;
  author?: T;
  publishedDate?: T;
  unpublishDate?: T;
  isFeatured?: T;
  isPinned?: T;
  showTableOfContents?: T;
  categories?: T;
  tags?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  relatedPosts?: T;
  relatedMenuItems?: T;
  readingTimeMinutes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  tenantId?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  tenantId?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  tenantId?: T;
  name?: T;
  email?: T;
  phone?: T;
  type?: T;
  status?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  tenantId?: T;
  title?: T;
  category?: T;
  media?: T;
  isFeatured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenantId?: T;
  businessName?: T;
  legalName?: T;
  taxId?: T;
  cuisineType?: T;
  priceRange?: T;
  mapsUrl?: T;
  mapsEmbedCode?: T;
  hours?:
    | T
    | {
        day?: T;
        openTime?: T;
        closeTime?: T;
        isClosed?: T;
        id?: T;
      };
  whatsappNumber?: T;
  deliverySettings?:
    | T
    | {
        enableDelivery?: T;
        deliveryUrls?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  reservationSettings?:
    | T
    | {
        provider?: T;
        providerUrl?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  googleAnalyticsId?: T;
  facebookPixelId?: T;
  customHeaderScripts?: T;
  customFooterScripts?: T;
  maintenanceMode?: T;
  showAnnouncementBar?: T;
  announcementText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav_select".
 */
export interface NavSelect<T extends boolean = true> {
  tenantId?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              icon?: T;
              badge?: T;
              newTab?: T;
              nofollow?: T;
              visibility?: T;
              id?: T;
              blockName?: T;
            };
        megaMenu?:
          | T
          | {
              label?: T;
              columns?:
                | T
                | {
                    title?: T;
                    links?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tenantId?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  bottomLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  tenantId?: T;
  metaTitlePattern?: T;
  metaDescription?: T;
  keywords?: T;
  canonicalUrl?: T;
  robots?: T;
  ogTitle?: T;
  ogDescription?: T;
  defaultOGImage?: T;
  ogSiteName?: T;
  twitterCard?: T;
  twitterSite?: T;
  twitterCreator?: T;
  jsonLd?: T;
  googleSiteVerification?: T;
  bingSiteVerification?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  tenantId?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  tenantId?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  tenantId?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  tenantId?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}